name: Web Deployment

on:
  push:
    branches:
      - 'main'
    paths:
        - 'apps/web/**'

env:
  VITE_API_URL: ${{ secrets.VITE_API_URL }}
  VITE_CLOUDFLARE_TURNSTILE_SITE_KEY: ${{ secrets.VITE_CLOUDFLARE_TURNSTILE_SITE_KEY }}
  
jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - run: bun run build --filter=web

      - run: |
          echo "{\"VITE_API_URL\": \"$VITE_API_URL\", \"VITE_CLOUDFLARE_TURNSTILE_SITE_KEY\": \"$VITE_CLOUDFLARE_TURNSTILE_SITE_KEY\"}" > secrets.json
  

      - run: |
          echo "{
            \"VITE_API_URL\": \"${{ secrets.VITE_API_URL }}\",
            \"COOKIE_SECRET\": \"${{ secrets.COOKIE_SECRET }}\",
            \"INSTANT_POSTGRES_API_KEY\": \"${{ secrets.INSTANT_POSTGRES_API_KEY }}\",
            \"APP_URL\": \"${{ secrets.APP_URL }}\",
            \"CLOUDFLARE_TURNSTILE_SECRET_KEY\": \"${{ secrets.CLOUDFLARE_TURNSTILE_SECRET_KEY }}\",
            \"UPSTASH_REDIS_REST_URL\": \"${{ secrets.UPSTASH_REDIS_REST_URL }}\",
            \"UPSTASH_REDIS_REST_TOKEN\": \"${{ secrets.UPSTASH_REDIS_REST_TOKEN }}\",
            \"CLOUDFLARE_API_TOKEN\": \"${{ secrets.CLOUDFLARE_API_TOKEN }}\",
            \"CLOUDFLARE_ACCOUNT_ID\": \"${{ secrets.CLOUDFLARE_ACCOUNT_ID }}\"
          }" > secrets.json
      
      - name: Upload secrets
        uses: cloudflare/wrangler-action@v3.6.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages secret bulk secrets.json --project-name=instant-postgres
          wranglerVersion: 3.58.0


      - name: Deploy
        uses: AdrianGonz97/refined-cf-pages-action@v1
        with:
          githubToken: ${{ secrets.GH_TOKEN }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: instant-postgres
          directory: ./build/client
          workingDirectory: ./apps/web
          deploymentName: web
          branch: main