name: Web Deployment

on:
  push:
    branches:
      - 'main'
    paths:
        - 'apps/web/**'

env:
  VITE_API_URL: ${{ secrets.VITE_API_URL }}
  
jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - run: bun run build --filter=web

      - run: |
          echo "{\"VITE_API_URL\": \"$VITE_API_URL\"}" > secrets.json
      
      - name: Upload secrets
        uses: cloudflare/wrangler-action@v3.6.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages secret bulk secrets.json --project-name=instant-postgres
          wranglerVersion: 3.58.0


      - name: Deploy
        uses: AdrianGonz97/refined-cf-pages-action@v1
        with:
          githubToken: ${{ secrets.GH_TOKEN }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: instant-postgres
          directory: ./build
          workingDirectory: ./apps/web
          deploymentName: web
          branch: main