name: Web Deployment

on:
  push:
    branches:
      - 'main'
    paths:
        - 'apps/web/**'
env:
  VITE_API_URL: http://localhost:8788
  
jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - run: bun run build --filter=web

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ../../apps/web/build --project-name=instant-postgres-web
          secrets: |
            VITE_API_URL
